<a href="https://colab.research.google.com/github/xing-wang-kai/ML_MODELAGEM_nao_supervisionnada/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MACHINE LEARNING

## MODELO DE APRENDIZAGEM NÃO SUPERVISIONADOS

Este modelo de apreendizagem de maquina não tem um padrão de teste e precisa de clustering para validar semelhanças entre dados e categorizar o mesmo.

In [1]:
import pandas as pd
import numpy as np

SEED = 123
np.random.seed(SEED)

url = "https://raw.githubusercontent.com/alura-cursos/alura-clustering-validation/base-de-dados/CC%20GENERAL.csv"

data = pd.read_csv(url, sep=',')
data

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,C10001,40.900749,0.818182,95.40,0.00,95.40,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12
1,C10002,3202.467416,0.909091,0.00,0.00,0.00,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12
2,C10003,2495.148862,1.000000,773.17,773.17,0.00,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.00,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,NaN,0.000000,12
4,C10005,817.714335,1.000000,16.00,16.00,0.00,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,C19186,28.493517,1.000000,291.12,0.00,291.12,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1000.0,325.594462,48.886365,0.500000,6
8946,C19187,19.183215,1.000000,300.00,0.00,300.00,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1000.0,275.861322,NaN,0.000000,6
8947,C19188,23.398673,0.833333,144.40,0.00,144.40,0.000000,0.833333,0.000000,0.666667,0.000000,0,5,1000.0,81.270775,82.418369,0.250000,6
8948,C19189,13.457564,0.833333,0.00,0.00,0.00,36.558778,0.000000,0.000000,0.000000,0.166667,2,0,500.0,52.549959,55.755628,0.250000,6
8949,C19190,372.708075,0.666667,1093.25,1093.25,0.00,127.040008,0.666667,0.666667,0.000000,0.333333,2,23,1200.0,63.165404,88.288956,0.000000,6

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CUST_ID                           8950 non-null   object
 1   BALANCE                           8950 non-null   float64
 2   BALANCE_FREQUENCY                 8950 non-null   float64
 3   PURCHASES                         8950 non-null   float64
 4   ONEOFF_PURCHASES                  8950 non-null   float64
 5   INSTALLMENTS_PURCHASES            8950 non-null   float64
 6   CASH_ADVANCE                      8950 non-null   float64
 7   PURCHASES_FREQUENCY               8950 non-null   float64
 8   ONEOFF_PURCHASES_FREQUENCY        8950 non-null   float64
 9   PURCHASES_INSTALLMENTS_FREQUENCY  8950 non-null   float64
 10  CASH_ADVANCE_FREQUENCY            8950 non-null   float64
 11  CASH_ADVANCE_TRX                  8950 non-null   int64
 12  PURCHASES_TRX                     8950 non-null   int64
 13  CREDIT_LIMIT                      8949 non-null   float64
 14  PAYMENTS                          8950 non-null   float64
 15  MINIMUM_PAYMENTS                  8637 non-null   float64
 16  PRC_FULL_PAYMENT                  8950 non-null   float64
 17  TENURE                            8950 non-null   int64
dtypes: float64(14), int64(3), object(1)
memory usage: 1.2+ MB

In [3]:
data.isna().sum()

CUST_ID                               0
BALANCE                               0
BALANCE_FREQUENCY                     0
PURCHASES                             0
ONEOFF_PURCHASES                      0
INSTALLMENTS_PURCHASES                0
CASH_ADVANCE                          0
PURCHASES_FREQUENCY                   0
ONEOFF_PURCHASES_FREQUENCY            0
PURCHASES_INSTALLMENTS_FREQUENCY      0
CASH_ADVANCE_FREQUENCY                0
CASH_ADVANCE_TRX                      0
PURCHASES_TRX                         0
CREDIT_LIMIT                          1
PAYMENTS                              0
MINIMUM_PAYMENTS                    313
PRC_FULL_PAYMENT                      0
TENURE                                0
dtype: int64

In [4]:
data.drop(['CUST_ID', 'TENURE'], axis=1, inplace=True)
data.head()

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT
0,40.900749,0.818182,95.40,0.00,95.4,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000
1,3202.467416,0.909091,0.00,0.00,0.0,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222
2,2495.148862,1.000000,773.17,773.17,0.0,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000
3,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,NaN,0.000000
4,817.714335,1.000000,16.00,16.00,0.0,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000

In [5]:
data.fillna(data.median(), inplace=True)
data.isna().sum()

BALANCE                             0
BALANCE_FREQUENCY                   0
PURCHASES                           0
ONEOFF_PURCHASES                    0
INSTALLMENTS_PURCHASES              0
CASH_ADVANCE                        0
PURCHASES_FREQUENCY                 0
ONEOFF_PURCHASES_FREQUENCY          0
PURCHASES_INSTALLMENTS_FREQUENCY    0
CASH_ADVANCE_FREQUENCY              0
CASH_ADVANCE_TRX                    0
PURCHASES_TRX                       0
CREDIT_LIMIT                        0
PAYMENTS                            0
MINIMUM_PAYMENTS                    0
PRC_FULL_PAYMENT                    0
dtype: int64

In [6]:
from sklearn.preprocessing import Normalizer

dataFrame = Normalizer().fit_transform(data.values)
dataFrame

array([[3.93555441e-02, 7.87271593e-04, 9.17958473e-02, ...,
        1.94178127e-01, 1.34239194e-01, 0.00000000e+00],
       [2.93875903e-01, 8.34231560e-05, 0.00000000e+00, ...,
        3.76516684e-01, 9.84037959e-02, 2.03923046e-05],
       [3.10798149e-01, 1.24560965e-04, 9.63068011e-02, ...,
        7.74852335e-02, 7.81351982e-02, 0.00000000e+00],
       ...,
       [2.27733092e-02, 8.11060955e-04, 1.40540698e-01, ...,
        7.90986945e-02, 8.02156174e-02, 2.43318384e-04],
       [2.65257948e-02, 1.64255731e-03, 0.00000000e+00, ...,
        1.03579625e-01, 1.09898221e-01, 4.92767391e-04],
       [1.86406219e-01, 3.33426837e-04, 5.46778061e-01, ...,
        3.15915455e-02, 4.41568390e-02, 0.00000000e+00]])

In [7]:
## O parametro N_INIT é quantas vezes devem retornar o mesmo valor para que a
## para que o resultado possa ser deterministico

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, n_init=10, max_iter=300)
y_predict = kmeans.fit_predict(dataFrame)

In [8]:
# As silhouettes são valores menores > 1 e maiores que -1 e que defimem o score do
# do agrupamento do K medias. Nesse caso o agrupamento foi de 0,36 superior ao valor
# de 0, o que garante uma boa precisão para o algoritmo selhecionado.
# Quanto mais próximo de 1 estiver o valor de silhouette mais separados estão os clusters.

from sklearn import metrics

labels = kmeans.labels_
silhouettes  = metrics.silhouette_score(dataFrame, labels, metric='euclidean')
silhouettes

0.3644026320471113

In [9]:
# Este modelo calcula dados entre o centroid dos clustters e retorna dados
# quanto mais próxmo de 0 melhor o modelo avaliativo do clutters

dbs = metrics.davies_bouldin_score(dataFrame, labels)
dbs

1.0758234649933396

In [11]:
## RECEBE ONSIDERAÇÃO DA DISPERSÃO ENTRE CLUSTERS
# USA CALCULOS DE VÁRIANÇAS

calinsk = metrics.calinski_harabasz_score(dataFrame, labels)
calinsk

3431.7843808489883

In [22]:
centroid = kmeans.cluster_centers_
centroid

array([[6.91174009e-02, 2.30606539e-04, 1.21226581e-01, 4.79772863e-02,
        7.33497068e-02, 2.41947578e-02, 1.72617514e-04, 3.36929404e-05,
        1.40042773e-04, 7.92242513e-06, 1.23760508e-04, 2.85805113e-03,
        9.43803334e-01, 1.53494462e-01, 5.68407863e-02, 7.58440293e-05],
       [3.32972556e-01, 2.68240066e-04, 1.58923673e-01, 3.62178588e-02,
        1.23089552e-01, 5.82140753e-02, 1.66817881e-04, 2.64295391e-05,
        1.47135264e-04, 1.92748591e-05, 4.26896159e-04, 3.86195702e-03,
        3.76646957e-01, 2.52402941e-01, 6.79571553e-01, 4.22964707e-06],
       [5.04120176e-01, 2.72279423e-04, 6.16154059e-02, 3.61332045e-02,
        2.55039227e-02, 2.53213629e-01, 6.73145543e-05, 2.56928004e-05,
        4.50515920e-05, 5.74730416e-05, 1.15776055e-03, 1.32966204e-03,
        7.19195953e-01, 1.66119756e-01, 1.79220769e-01, 5.52512128e-07],
       [1.59970277e-01, 2.45420653e-04, 4.37832758e-01, 2.56342445e-01,
        1.81661269e-01, 2.57701902e-02, 2.04632150e-04, 8.87805917e-05,
        1.51042337e-04, 9.36227386e-06, 1.69268877e-04, 6.17437812e-03,
        6.04822057e-01, 4.02343053e-01, 8.52508929e-02, 7.25704005e-05],
       [2.35141479e-01, 2.16555293e-04, 6.03857074e-02, 3.44170171e-02,
        2.59739049e-02, 4.00128071e-01, 5.26401668e-05, 2.04882397e-05,
        3.51921361e-05, 6.54864556e-05, 1.57199032e-03, 1.12217156e-03,
        5.35089146e-01, 5.98040052e-01, 1.04348171e-01, 2.77498236e-05]])

In [29]:
for cols in range(len(centroid[0])):
  print(data.columns.values[cols])
  print(f"{centroid[:, cols].var():.4f}")
  print("*"*50)

BALANCE
0.0224
**************************************************
BALANCE_FREQUENCY
0.0000
**************************************************
PURCHASES
0.0196
**************************************************
ONEOFF_PURCHASES
0.0076
**************************************************
INSTALLMENTS_PURCHASES
0.0036
**************************************************
CASH_ADVANCE
0.0226
**************************************************
PURCHASES_FREQUENCY
0.0000
**************************************************
ONEOFF_PURCHASES_FREQUENCY
0.0000
**************************************************
PURCHASES_INSTALLMENTS_FREQUENCY
0.0000
**************************************************
CASH_ADVANCE_FREQUENCY
0.0000
**************************************************
CASH_ADVANCE_TRX
0.0000
**************************************************
PURCHASES_TRX
0.0000
**************************************************
CREDIT_LIMIT
0.0360
**************************************************
PAYMENTS
0.0280
**************************************************
MINIMUM_PAYMENTS
0.0542
**************************************************
PRC_FULL_PAYMENT
0.0000
**************************************************